language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
before_install:
  - test "$TRAVIS_OS_NAME" != linux || sudo apt-get -qq update
  - test "$TRAVIS_OS_NAME" != linux || sudo apt-get -qq install libwxgtk3.0-dev libavcodec-dev libavformat-dev libproj-dev libswscale-dev mesa-common-dev libglu1-mesa-dev libx11-dev libxext-dev x11proto-core-dev liblocale-po-perl unifont sgmltools-lite jadetex docbook-to-man w3m
  - test "$TRAVIS_OS_NAME" != osx || brew update
  - test "$TRAVIS_OS_NAME" != osx || brew install netpbm
  - test "$TRAVIS_OS_NAME" != osx || sudo cpan -T -i Locale::PO < /dev/null
script:
  - autoreconf -fiv
  - test "$TRAVIS_OS_NAME" = osx || ./configure
  - test "$TRAVIS_OS_NAME" = osx || make
  - test "$TRAVIS_OS_NAME" = osx || make check
  - test "$TRAVIS_OS_NAME" != osx || ./buildmacosx.sh
branches:
  only:
    - master
