dist: trusty
language: cpp
cache: ccache
matrix:
  include:
    - compiler: gcc
      os: linux
      sudo: false
      addons:
        apt:
          packages:
            - libwxgtk3.0-dev
            - libavcodec-dev
            - libavformat-dev
            - libproj-dev
            - libswscale-dev
            - mesa-common-dev
            - libglu1-mesa-dev
            - libx11-dev
            - libxext-dev
            - ghostscript
            - netpbm
            - x11proto-core-dev
            - liblocale-po-perl
            - unifont
            - sgmltools-lite
            - jadetex
            - docbook-utils
            - w3m
      script:
        - autoreconf -fiv
        - ./configure
        - make
        - make check VERBOSE=1
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - ccache
            - ffmpeg
            - gettext
            - gnu-tar
            - netpbm
            - proj
            - wxmac
      before_install:
        - brew link --force gettext
        - sudo cpan -T -i local::lib < /dev/null
        - sudo cpan -I -T -i Locale::PO < /dev/null
        - echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc
      script:
        - export PATH=/usr/local/opt/ccache/libexec:$PATH
        - autoreconf -fiv
        - V=`sed -e 's/^AC_INIT[^,]*, *\[\([^]]*\)\].*/\1/p;d' configure.ac` ; curl https://survex.com/software/$V/survex-$V.tar.gz | gtar --strip-components=1 --skip-old-files -zxf - ; ls -lrt lib ; touch lib/unifont.pixelfont lib/preload_font.h; echo ; ls -lrt doc; touch doc/*.1 doc/manual.txt doc/manual.pdf doc/manual/stampfile
        - ./configure
        - make
        - make check VERBOSE=1
    - os: osx
      # xcode8.3 needs more time than travis allows just to install
      # dependencies from homebrew.
      osx_image: xcode9
      addons:
        homebrew:
          update: true
          packages:
            - ccache
            - ffmpeg
            - gettext
            - gnu-tar
            - netpbm
            - proj
            - wxmac
      before_install:
        - brew link --force gettext
        - sudo cpan -T -i local::lib < /dev/null
        - sudo cpan -I -T -i Locale::PO < /dev/null
        - echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc
      script:
        - export PATH=/usr/local/opt/ccache/libexec:$PATH
        - autoreconf -fiv
        - V=`sed -e 's/^AC_INIT[^,]*, *\[\([^]]*\)\].*/\1/p;d' configure.ac` ; curl https://survex.com/software/$V/survex-$V.tar.gz | gtar --strip-components=1 --skip-old-files -zxf - ; ls -lrt lib ; touch lib/unifont.pixelfont lib/preload_font.h; echo ; ls -lrt doc; touch doc/*.1 doc/manual.txt doc/manual.pdf doc/manual/stampfile
        - ./configure
        - make
        - make check VERBOSE=1
branches:
  only:
    - master
