language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
before_install:
  - test "$TRAVIS_OS_NAME" != linux || sudo apt-get -qq update
  - test "$TRAVIS_OS_NAME" != linux || sudo apt-get -qq install libwxgtk3.0-dev libavcodec-dev libavformat-dev libproj-dev libswscale-dev mesa-common-dev libglu1-mesa-dev libx11-dev libxext-dev x11proto-core-dev liblocale-po-perl unifont sgmltools-lite jadetex docbook-utils w3m
  - test "$TRAVIS_OS_NAME" != osx || brew update
  - test "$TRAVIS_OS_NAME" != osx || brew install netpbm
  - test "$TRAVIS_OS_NAME" != osx || sudo cpan -T -i local::lib < /dev/null
  - test "$TRAVIS_OS_NAME" != osx || sudo cpan -I -T -i Locale::PO < /dev/null
  - if test "$TRAVIS_OS_NAME" = osx ; then echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc ; fi
script:
  - autoreconf -fiv
  - if test "$TRAVIS_OS_NAME" = osx ; then wget http://unifoundry.com/pub/unifont-9.0.02/font-builds/unifont-9.0.02.hex.gz && gunzip unifont-9.0.02.hex.gz && mv unifont-9.0.02.hex lib/unifont.hex ; fi
  - test "$TRAVIS_OS_NAME" = osx || ./configure
  - test "$TRAVIS_OS_NAME" = osx || make
  - test "$TRAVIS_OS_NAME" = osx || make check
  - test "$TRAVIS_OS_NAME" != osx || touch doc/3dtopos.1 doc/aven.1 doc/cad3d.1 doc/cavern.1 doc/diffpos.1 doc/extend.1 doc/sorterr.1
  - test "$TRAVIS_OS_NAME" != osx || mkdir -p doc/manual
  - test "$TRAVIS_OS_NAME" != osx || touch doc/manual.pdf doc/manual.txt doc/manual/stampfile
  - test "$TRAVIS_OS_NAME" != osx || ./buildmacosx.sh
branches:
  only:
    - master
