language: cpp
compiler:
  - clang
  - gcc
script:
  - autoreconf -fiv
  - test "$TRAVIS_OS_NAME" = osx || ./configure
  - test "$TRAVIS_OS_NAME" = osx || make
  - test "$TRAVIS_OS_NAME" = osx || make check
  - test "$TRAVIS_OS_NAME" != osx || ./buildmacosx.sh
branches:
  only:
    - master
