name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [macos-10.15, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: packages
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install --no-install-recommends automake pkg-config gcc libwxgtk3.0-gtk3-dev libavcodec-dev libavformat-dev libproj-dev libswscale-dev mesa-common-dev libglu1-mesa-dev libx11-dev libxext-dev ghostscript netpbm x11proto-core-dev liblocale-po-perl unifont docbook-utils w3m gettext
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install autoconf automake ffmpeg gettext gnu-tar netpbm proj wxmac
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
    - name: prebuild
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          brew link --force gettext
          sudo cpan -T -i Locale::PO
          echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc
        fi
    - name: autoconf
      run: autoreconf -fiv
    - name: configure
      run: ./configure
    - name: make
      run: make
    #  - name: check
    #   run: make check
