name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: inkscape ppa
        run: sudo add-apt-repository universe && sudo add-apt-repository ppa:inkscape.dev/stable
      - name: dependencies
        run: sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install --no-install-recommends automake pkg-config gcc g++ libwxgtk3.0-gtk3-dev libavcodec-dev libavformat-dev libproj-dev libswscale-dev mesa-common-dev libglu1-mesa-dev libx11-dev libxext-dev ghostscript netpbm x11proto-core-dev liblocale-po-perl unifont docbook-utils w3m gettext inkscape
      - name: autoconf
        run: autoreconf -fiv
      - name: configure
        run: ./configure
      - name: package
        run: make dist
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: survex-source-package
          path: survex-?.?.?.tar.gz
  build:
    needs: package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-latest]

    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: survex-source-package
      - name: unzip
        run: mkdir packaged-src && tar -C packaged-src --strip-components=1 -xvf survex-?.?.?.tar.gz
      - name: dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install --no-install-recommends libwxgtk3.0-gtk3-dev libproj-dev libavcodec-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ffmpeg netpbm proj wxwidgets
            sudo cpan -T -i Locale::PO
            echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
      - name: build
        working-directory: packaged-src
        run: ./configure --prefix=$PWD/package-bin && make -j$(nproc) 2>/dev/null && make install
      - name: postbuild
        working-directory: packaged-src
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            APP_PATH=package-bin/Aven.app make create-aven-app
            mv ./package-bin/bin/* ./package-bin/Aven.app/Contents/MacOS
          fi
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: survex-binary-package
          path: packaged-src/package-bin/
    #  - name: check
    #   run: make check
